feat: variables refactor
kubeshop/testkube-executor-k6 pull request #17
Opened 2022-05-18 11:54 UTC by exu

## Pull request description 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2022-05-18 12:02 UTC, vsukhin approved these changes

2022-05-18 14:55 UTC, lreimer requested changes
I think the changes have been made on an outdated source version. Also should we use a beta001 version as dependency, or better a more stable one?

2022-05-19 10:49 UTC, exu commented on pkg/runner/runner.go
> +	for _, v := range execution.Variables {
🤦 old main branch - closing this one - will do on top of main branch once more

2022-05-19 10:50 UTC, exu commented on go.mod
> +	github.com/kubeshop/testkube v1.1.10-beta001
no with those changes - I'll change those versions after merge testkube to main branch - just want to release everything in one shot

2022-05-19 10:51 UTC, exu commented on go.mod
> +	github.com/kubeshop/testkube v1.1.10-beta001
It'll be 1.1.10+ after merge

2022-05-19 10:51 UTC, closed without merging